version: '2'

networks:
  network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - network
    links:
      - mysql
#    logging:
#      driver: awslogs
#      options:
#        awslogs-region: "us-east-1"
#        awslogs-group: "laravel"
#        awslogs-create-group: "true"
    env_file:
        - docker-compose.env

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - network
#    logging:
#      driver: awslogs
#      options:
#        awslogs-region: "us-east-1"
#        awslogs-group: "nginx"
#        awslogs-create-group: "true"
    links:
        - app

  mysql:
    image: mysql:5.7
#    logging:
#      driver: awslogs
#      options:
#        awslogs-region: "us-east-1"
#        awslogs-group: "postgresql"
#        awslogs-create-group: "true"
    #volumes:
    #  - dbdata:/var/lib/postgresql/data
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DB
      - MYSQL_USER
      - MYSQL_ROOT_PASSWORD=test123
    env_file:
        - docker-compose.env
    networks:
      - network


#volumes:
#  dbdata:
#    driver: local